spring:
  application:
    name: house-portal
  profiles:
    active: dev #默认为开发环境
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  check-config-location: false
  global-config:
    db-config:
      id-type: auto
      table-prefix:
  type-aliases-package: com.yunzhu.house.model
  type-enums-package: com.yunzhu.house.enums

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: house-portal-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui/
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.map
      - /favicon.ico
      - /druid/**
      - /actuator/**
      - /sso/**
      - /home/**
      - /product/**
      - /brand/**

# 自定义redis key
redis:
  database: house
  key:
    authCode: 'ums:authCode'
    orderId: 'oms:orderId'
    member: 'ums:member'
  expire:
    authCode: 90 # 验证码超期时间
    common: 86400 # 24小时

# 消息队列定义
rabbitmq:
  queue:
    name:
      cancelOrder: cancelOrderQueue


# 短信发送
aliyun:
  sms:
      accessKeyId: 'LTAICNmks8S1RMux'
      accessKeySecret: 'C07WZ98KO6AdkbNnj2k85Jq6BGmAcr'
      signName: '阿里云短信测试'
      templateCode: 'SMS_154950909'
      region: 'cn-hangzhou'
      endpoint: 'dysmsapi.aliyuncs.com'

#微信授权登录
wx:
  open:
    app_id: 'wxed9954c01bb89b47'
    app_secret: 'a7482517235173ddb4083788de60b90e'
    redirect_url: 'http://guli.shop/api/ucenter/wx/callback'





